#!/bin/bash

if [ $# -lt 3 ]; then
    echo ""
    echo "Script for play some tones based on a frequency and duration, util to test tones for GRUB_INIT_TUNE ."
    echo ""
    echo "This script need to have installed \"sox\" on your system."
    echo ""
    echo "Usage: $0 tempo freq dur [freq dur freq dur...]" >&2
    echo ""
    echo "Based on this thread: https://askubuntu.com/questions/76309/play-a-sound-before-or-after-grub-loads"
    echo ""
    echo "Frequency Table for Notes: http://pages.mtu.edu/~suits/notefreq446.html"
    echo ""
    echo "For a list of tones you can see the \"README_grub-playtune.md\" file."

    exit 1
fi

tempo=$1; shift

tmpdir=$(mktemp -d)

while [ -n "$*" ]; do
    freq=$1; shift
    dur=$1;  shift
    dur=$(echo "$dur*(60/$tempo)"|bc -l)
    sox -e mu-law -r 8000 -n -t raw - synth $dur sine $freq >>$tmpdir/grubtune.ul 2> /dev/null
done

play -q -c1 -r 8000 $tmpdir/grubtune.ul

rm -r $tmpdir
